# Generated by Django 6.1.1 on 2026-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(choices=[('general', 'General'), ('cuenta', 'Mi cuenta'), ('compras', 'Compras y pedidos'), ('inventario', 'Productos e inventario'), ('administracion', 'Administración')], default='general', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['categoria', 'orden'],
            },
        ),
    ]
