# Generated by Django 6.1.1 on 2026-10-06 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], max_length=10)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=10)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500)),
                ('tamano', models.PositiveBigIntegerField(default=0, help_text='Bytes')),
                ('detalle_error', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'permissions': [('gestionar_respaldos', 'Puede generar, descargar y restaurar respaldos')],
            },
        ),
    ]
