# Generated by Django 6.1.1 on 2026-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único del producto. Se usa para buscarlo rápidamente.', max_length=30, unique=True, verbose_name='Código (SKU)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('electricos', 'Eléctricos'), ('interiores', 'Interiores'), ('ferreteria', 'Ferretería'), ('iluminacion', 'Iluminación')], default='electricos', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Normal')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Oferta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción Corta')),
                ('instalacion', models.TextField(verbose_name='Uso e Instalación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado_en_inicio', models.BooleanField(default=False, verbose_name='Destacado en Inicio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': [],
            },
        ),
    ]
