# Generated by Django 6.1.1 on 2026-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, help_text='Una característica por línea. Ejemplo: Potencia: 20W', verbose_name='Características Técnicas'),
        ),
    ]
